---
services:
  tsukasa:
    image: kisaragi29/tsukasa:latest
    container_name: tsukasa
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./data:/root/nltk_data
      - ./app_tsuka.py:/app/app_tsuka.py
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    restart: unless-stopped
