---
services:
  tsukasa:
    image: kisaragi29/tsukasa:latest
    container_name: tsukasa
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - tsukasa_data:/root/nltk_data
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    restart: unless-stopped

volumes:
  tsukasa_data:
